name: docker-cli-publish

on:
  workflow_dispatch:
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4.1.1
      - name: docker log in
        run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin         
        env:
          CR_PAT: ${{ secrets.CONTAINER_TOKEN }}
      - name: build container
        id: build-container
        run: |
          docker build . -t ghcr.io/terraform-test-modules/package-publish-repo:1.0
    #  - name: pull image
     #   run: |
     #     sleep 5m
    #      docker pull ghcr.io/uppercase-test-org/hello-world-docker-action-image:1.2
      - name: publish the container
        run: |
          docker push ghcr.io/terraform-test-modules/package-publish-repo:1.0
           
